### ISSUE TITLE
emacs-powerthesaurus has stopped working, any help, pls?

### ISSUE THREAD

**Issue by touxstone** [SavchenkoValeriy/emacs-powerthesaurus#8] opened 2019-02-08 03:00 UTC
Hi, have anyone try this (gorgeous) package lately? all of a sudden it has stopped working...  The only output I got when calling for `powerthesaurus-lookup-word-at-point` now is:
```elisp
REQUEST [error] Error (error) while connecting to https://www.powerthesaurus.org/happen/synonyms.
```
Any help would be appreciated...

**Comment by hebdon** [comment] 2019-02-13 23:27
Same issue here!

**Comment by pierrebonbon** [comment] 2019-02-16 00:07
getting the exact same issue.

**Comment by manuel-uberti** [comment] 2019-02-19 07:11
I can confirm the issue too.

**Comment by manuel-uberti** [comment] 2019-02-19 07:14
I am getting 403 when hitting the URL https://www.powerthesaurus.org/

**Comment by manuel-uberti** [comment] 2019-02-19 12:32
And BTW, there is already an open issue on this: https://github.com/SavchenkoValeriy/emacs-powerthesaurus/issues/6

**Comment by SavchenkoValeriy** [comment] 2019-06-22 07:07
This issue is a duplicate of #6

**Closed** 2019-06-22 07:07 UTC

**Comment by matthew-piziak** [comment] 2019-07-10 03:08
I'm still getting this as of 9616249.

**Comment by SavchenkoValeriy** [comment] 2019-07-10 06:27
@matthew-piziak can you please check requests that your browser sends when you browse powerthesaurus. I think it might be not enough to pass user-agent in some cases.

Also some times I need to go to the website and check the checkbox that I'm not a robot. It works fine after that. It might be a workaround in your case as well.

**Comment by symbiont-matthew-piziak** [comment] 2019-07-10 18:17
> please check requests that your browser sends when you browse powerthesaurus

I can access the URL manually in Firefox if that's what you mean. Or are you saying that the request itself uses a browser for some reason?

**Comment by matthew-piziak** [comment] 2019-07-10 18:18
> can you please check requests that your browser sends when you browse powerthesaurus

I can access the URL manually in Firefox if that's what you mean.

**Comment by SavchenkoValeriy** [comment] 2019-07-10 22:08
Your browser sends HTTP requests to get the page (one or more to different sources). You can track it with special plugins. One plugin for Chrome is called HTTP Trace, for example. I looked at what my browser sent to get the data from powerthesaurus and replicated it in the request, that the lisp code sends. 

So, my comment was in two parts. Check that it works in the web version (:check:).
And check what kind of request does your browser send so it works. It will be very helpful if you can get the request.

**Comment by symbiont-matthew-piziak** [comment] 2019-07-10 22:34
I still don't understand what browsers have to do with Emacs.

**Comment by matthew-piziak** [comment] 2019-07-10 22:35
I still don't understand what browsers have to do with Emacs.

**Comment by matthew-piziak** [comment] 2019-07-10 22:36
Oh weird. It's working for me now...

**Comment by matthew-piziak** [comment] 2019-07-10 22:37
Were you asking me to compare the HTTP request in Firefox/Chrome with the HTTP request in my Emacs?
